### ISSUE TITLE
Power for the ESP's?

### ISSUE THREAD

**Issue by zmrow** [gwilken/ariadne-io#1]
Hey there - this project is awesome!  Great work.

Curious how you're powering the ESP's?  The pictures show a red/black coming in, but I didn't see any voltage converters, etc.

**Comment by gwilken** [comment]
Hey thanks! The power converters are inside the enclosures. They are just simple 12v to 3.3v down steppers. You could definitely build a better solution onto the circuit boards themselves. These were cheap, easy, and seemed overbuilt for the job.

https://www.amazon.com/gp/product/B00C64ZJYU/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1

**Comment by zmrow** [comment]
Thanks!
