### ISSUE TITLE
Pelican case

### ISSUE THREAD

**Issue by mookiejones** [gwilken/ariadne-io#2]
Where did you get the cases from?

**Comment by gwilken** [comment]
That case is a Pelican 1050:
https://www.amazon.com/Pelican-1050-Micro-Carabiner-Clear/dp/B001PYL1BM/ref=sr_1_2?ie=UTF8&qid=1503939966&sr=8-2&keywords=pelican+case+1050

Probably a better way to do it, but it works. An issue I ran into was that the Pi fits pretty tight width wise, and that doesn't leave room for your typical micro usb power cord to be sticking out, so I found a right angle adaptor that works:
https://www.amazon.com/gp/product/B01C6031MA/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1

I drilled holes into the pelican case and added water proof wiring glands to keep everything dry, you'll need some big ones to pass the end of the USB cables through, I use these for smaller cables which should give you an idea of what you're looking for:
https://www.amazon.com/gp/product/B01GJ03AUQ/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1

hope that helps!
